### ISSUE TITLE
Expose the Producer object instead of just the create function

### ISSUE THREAD

**Issue by offero** [bbc/sqs-producer#13]
I wanted to Promisify the Producer class using Bluebird and realized that it wasn't even accessible to me to do so. Please expose class itself instead of just the create function.

**Comment by robinjmurphy** [comment]
Hello @offero. Can you not promisify the object returned by `createClient`?

**Comment by offero** [comment]
I can and I did that as a temporary solution, but that means that you have to promisify the new object each time. Best practice is to promisify the prototype functions so that you only have that overhead once when you first require it.

**Comment by offero** [comment]
SQS Consumer exposes the object and a static create function as well:

https://github.com/bbc/sqs-consumer/blob/master/index.js

**Comment by robinjmurphy** [comment]
Ok. Thanks for explaining. We'll take a look at it this week @offero. We might be able to just take the same approach as in the consumer.
