### ISSUE TITLE
Retrieve messageId

### ISSUE THREAD

**Issue by yarandoo** [bbc/sqs-producer#14]
Hi, 

it would be very useful to have the MessageId generated by AWS when the message gets pushed. Is there any way to obtain this information in the callback notification?

Thanks!

**Comment by robinjmurphy** [comment]
Hi @yarandoo. We currently don't return any information about the messages. Would be happy to add this, maybe by simply returning the AWS response in the callback.

If you're interested in submitting a PR, the code to do this will be around here https://github.com/bbc/sqs-producer/blob/master/lib/producer.js#L121. There's some recursion going on that you'll need to be aware of as we send messages in batches.

**Comment by nitinsmartsense** [comment]
+1 for simply return aws response

**Comment by aalimovs** [comment]
@robinjmurphy would you be able to have a look and merge either @thlgrant or @robertyoung (with tests) PRs?
