### ISSUE TITLE
sending Message makes two entry of one message into aws SQS using lambda to send the message

### ISSUE THREAD

**Issue by faisalpathan** [bbc/sqs-producer#22]
var uuid = require('uuid/v1');
var Producer = require('sqs-producer');
var AWS = require('aws-sdk');

exports.handler = (event, context, callback) => {

	var producer = Producer.create({
	  queueUrl: QUEUE_URL,
	  region: 'eu-west-1'
	});

	var dataToSqsQueue = JSON.stringify(event);
	console.log(dataToSqsQueue);

	producer.send({
	  id:uuid(),
	  body: dataToSqsQueue,
	  groupId: uuid(),
	  deduplicationId: uuid() // typically a hash of the message body 
	}, function(err) {
	  if (err) console.log(err);
	});
};

**Comment by niklasR** [comment]
Unless you use a FIFO queue, SQS does not guarantee that there won't be duplicates.
> Standard queues provide at-least-once delivery, which means that each message is delivered at least once.
> FIFO queues provide exactly-once processing, which means that each message is delivered once and remains available until a consumer processes it and deletes it. Duplicates are not introduced into the queue.
(https://aws.amazon.com/sqs/faqs/)
