### ISSUE TITLE
Consider using debug

### ISSUE THREAD

**Issue by DiegoRBaquero** [bbc/sqs-producer#27]
I was recently getting a "Failed to send message: 1" with no info.

Please consider adding [debug](https://www.npmjs.com/package/debug) to add optional debugging. 

Adding a quick console log to the result from AWS showed that I was adding an extra param not expected, but `sqs-producer` would not forward this error and no other info was available.

**Comment by andrii33** [comment]
It would be helpful to have the debug feature.

**Comment by miso-kyoungminkim** [comment]
I met same experience, too
Can I contribute for this issue?
