### ISSUE TITLE
When is v2.0 getting published?

### ISSUE THREAD

**Issue by koresar** [bbc/sqs-producer#45]
Hello maintainers.

Looking at the Milestone "v2.0" it was recently reached: https://github.com/bbc/sqs-producer/milestones

Is there anything else you wanted to add to the milestone before publishing v2.0?
If not, how else can I help publishing v2.0?

**Comment by nspragg** [comment]
@koresar - we will publish V2 within the next 48 hours.

**Comment by nspragg** [comment]
@koresar - V2 has been released. Thanks for your contribution.

**Comment by koresar** [comment]
Thank you for the care about us. 👍
