### ISSUE TITLE
Is ts-node-register production dependency intended?

### ISSUE THREAD

**Issue by koresar** [bbc/sqs-producer#46]
As per contribution guide rising this important question before submitting a 1-line PR.

I found that `ts-node-register` is a production dependency of the module. `ts-node-register` has few unnecessary subdependencies.

I would assume including this was an incident. The `ts-node-register` is not used anywhere.

Should I submit a PR to remove this line from `package.json`?

**Comment by nspragg** [comment]
Thanks, @koresar 

`ts-node-register` should not be in `dependencies`. This has been removed and a patch released.
