### ISSUE TITLE
Unlock aws-sdk dependency

### ISSUE THREAD

**Issue by giacomomagini** [bbc/sqs-producer#64]
**Describe the bug**
aws-sdk version is locked to version 2.677.0. This version has several security vulnerabilities. Can you unlock it in order to use a compatible version added to the project where we add this package as dependency?

**Comment by DiegoRBaquero** [comment]
It's a range, you can refresh your package-lock with latest.

**Comment by nicholasgriffintn** [comment]
This will also be updated to `^2.1271.0` in the next package deployment.
