### ISSUE TITLE
Wait for message result

### ISSUE THREAD

**Issue by neumartin** [bbc/sqs-producer#69]
I trying to use this package in microservice context.
I need to send a message and wait for the result, for example, send a filter and get the list of objects.
How can I wait to get the message results?

Thanks!

**Comment by topmonroe9** [comment]
> I trying to use this package in microservice context. I need to send a message and wait for the result, for example, send a filter and get the list of objects. How can I wait to get the message results?
> 
> Thanks!

I am not sure that is possible. Same as with AMQP protocal in NestJS - you will not recieve a response itself for that message, just a message status.
