### ISSUE TITLE
[Bug]: `npm link sqs-producer` does not work in new v3

### ISSUE THREAD

**Issue by koresar** [bbc/sqs-producer#91]
### Describe the bug

Install globally. Link it. The `npm link` fails.

### Your minimal, reproducible example

npm i -g sqs-producer && npm link sqs-producer

### Steps to reproduce

```sh
> npm i -g sqs-producer
> npm link sqs-producer
npm ERR! code 127
npm ERR! path ~/.nvm/versions/node/v16.18.1/lib/node_modules/sqs-producer
npm ERR! command failed
npm ERR! command sh -c -- npm run build
npm ERR! > sqs-producer@3.0.1 build
npm ERR! > npm run clean && tsc
npm ERR! 
npm ERR! 
npm ERR! > sqs-producer@3.0.1 clean
npm ERR! > rm -fr dist/*
npm ERR! sh: tsc: command not found
```

### Expected behavior

No errors. `sqs-producer` installed globally and working fine.

### How often does this bug happen?

Every time

### Platform

All

### Package version

3.0, 3.1

### Additional context

Offtopic: This bug template is a bit annoying. It should not mandate for "minimal reproducible example" as a URL

**Comment by nicholasgriffintn** [comment]
The error that you are getting here is 'tsc: command not found', presumably that means that typescript is not installed, which is a dev dependency but obviously not a production one (not needed after you build it).

**Comment by nicholasgriffintn** [comment]
Should be sorted in `3.1.0`, changed to prepublishOnly
