### ISSUE TITLE
[Feature]: env variable AWS_REGION is not used during producer creation

### ISSUE THREAD

**Issue by rcadelw33** [bbc/sqs-producer#94]
### Describe the bug

Env variable AWS_REGION is not used during producer instantiation

### Your minimal, reproducible example

https://codesandbox.io/s/frosty-margulis-vrh93k?file=/src/index.js

### Steps to reproduce

// those code doesn't generate the same result
Producer.create({
      queueUrl: "myQueueUrl"
    })

Producer.create({
      queueUrl: "myQueueUrl",
      region: process.env.AWS_REGION
    })

### Expected behavior

process.env.AWS_REGION should be used during creation

### How often does this bug happen?

Every time

### Platform

all

### Package version

3.1.3

**Comment by nicholasgriffintn** [comment]
Hey, thanks for raising this!

As it's not intended behaviour, I'm going to re label this. Thanks for putting a PR in though, we appreciate it :)

**Comment by nicholasgriffintn** [comment]
Published to https://github.com/bbc/sqs-producer/releases/tag/v3.2.0 thanks!
